# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vital Signs
safe: true
lsi: false
email: matth@localdata.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
category-list: [Transportation, Land & People, Economy, Environment]
collections:
  topics:
    output: true
  measures:
    output: true
defaults:
  - scope:
      path: "topics"
    values:
      layout: "topic"
  - scope:
      path: "measures"
    values:
      layout: "measure"

# Build settings
markdown: kramdown

# Prose settings
prose:
  metadata:
    _topics:
      - name: "categories"
        field:
          label: "Categories"
          element: "multiselect"
          options:
            - name: "Transportation"
              value: "Transportation"
            - name: "Land & People"
              value: "Land & People"
            - name: "Economy"
              value: "Economy"
            - name: "Environment"
              value: "Environment"
      - name: "methods"
        field:
          label: "Methods"
          element: "textarea"

